use crate::models::Question;
use uuid::Uuid;

pub fn get_questions() -> Vec<Question> {
    vec![
        // ========== TIER 0: min_affinity = 0 (Icebreakers) ==========
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have the ability to fly or be invisible?".to_string(),
            options: vec!["Fly".to_string(), "Invisible".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather always be 10 minutes late or always be 20 minutes early?".to_string(),
            options: vec!["10 mins late".to_string(), "20 mins early".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What's your go-to comfort food?".to_string(),
            options: vec!["Pizza".to_string(), "Ice cream".to_string(), "Soup".to_string(), "Chocolate".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather live in a big city or a small town?".to_string(),
            options: vec!["Big city".to_string(), "Small town".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Morning person or night owl?".to_string(),
            options: vec!["Morning person".to_string(), "Night owl".to_string(), "Neither".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have a rewind button or a pause button on your life?".to_string(),
            options: vec!["Rewind".to_string(), "Pause".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "If you could have dinner with anyone, alive or dead, who would it be?".to_string(),
            options: vec!["A historical figure".to_string(), "A celebrity".to_string(), "A family member".to_string(), "A fictional character".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather explore space or the deep ocean?".to_string(),
            options: vec!["Space".to_string(), "Deep ocean".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What type of music do you gravitate toward?".to_string(),
            options: vec!["Pop / Top 40".to_string(), "Rock / Alternative".to_string(), "Hip-hop / R&B".to_string(), "Classical / Jazz".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather lose all of your money or all of the pictures you have ever taken?".to_string(),
            options: vec!["Lose money".to_string(), "Lose photos".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Dogs, cats, or something else?".to_string(),
            options: vec!["Dogs".to_string(), "Cats".to_string(), "Both equally".to_string(), "Something else".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather be able to talk to animals or speak all foreign languages?".to_string(),
            options: vec!["Talk to animals".to_string(), "Speak all languages".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have unlimited free flights or unlimited free hotel stays?".to_string(),
            options: vec!["Free flights".to_string(), "Free hotels".to_string()],
            min_affinity: 0,
            language: "en".to_string(),
            translatable: true,
        },

        // ========== TIER 1: min_affinity = 2 (Getting to know you) ==========
        Question {
            id: Uuid::new_v4(),
            text: "How do you usually spend your weekends?".to_string(),
            options: vec!["Socializing".to_string(), "Staying in / relaxing".to_string(), "Outdoor activities".to_string(), "Working on projects".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather never use social media again or never watch TV/movies again?".to_string(),
            options: vec!["No social media".to_string(), "No TV/movies".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What matters more in a friendship?".to_string(),
            options: vec!["Loyalty".to_string(), "Honesty".to_string(), "Fun times together".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather live without music or without movies?".to_string(),
            options: vec!["Without music".to_string(), "Without movies".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "How do you handle disagreements?".to_string(),
            options: vec!["Talk it out immediately".to_string(), "Take time to cool off first".to_string(), "Avoid conflict".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather always know the truth or live in blissful ignorance?".to_string(),
            options: vec!["Always know the truth".to_string(), "Blissful ignorance".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What's your ideal vacation style?".to_string(),
            options: vec!["Beach & relaxation".to_string(), "City & culture".to_string(), "Adventure & nature".to_string(), "Road trip".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather be famous but misunderstood or unknown but deeply fulfilled?".to_string(),
            options: vec!["Famous but misunderstood".to_string(), "Unknown but fulfilled".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have the power to read minds or predict the future?".to_string(),
            options: vec!["Read minds".to_string(), "Predict the future".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Pick your ideal superpower:".to_string(),
            options: vec!["Teleportation".to_string(), "Time travel".to_string(), "Super strength".to_string(), "Telepathy".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What kind of learner are you?".to_string(),
            options: vec!["Visual".to_string(), "Hands-on".to_string(), "Reading/writing".to_string(), "Listening".to_string()],
            min_affinity: 2,
            language: "en".to_string(),
            translatable: true,
        },

        // ========== TIER 2: min_affinity = 5 (Deeper personality) ==========
        Question {
            id: Uuid::new_v4(),
            text: "What do you value most in life?".to_string(),
            options: vec!["Family".to_string(), "Career / ambition".to_string(), "Experiences / adventure".to_string(), "Inner peace".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have a job you love that pays little or a job you hate that pays a lot?".to_string(),
            options: vec!["Love it, low pay".to_string(), "Hate it, high pay".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "How do you recharge after a stressful day?".to_string(),
            options: vec!["Alone time".to_string(), "Talking to someone".to_string(), "Physical activity".to_string(), "Creative outlet".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather be remembered for being kind or being brilliant?".to_string(),
            options: vec!["Kind".to_string(), "Brilliant".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What's your relationship with risk?".to_string(),
            options: vec!["Love taking risks".to_string(), "Calculated risks only".to_string(), "Prefer safety".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Do you believe people can truly change?".to_string(),
            options: vec!["Yes, absolutely".to_string(), "Only with effort".to_string(), "Rarely".to_string(), "No".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather know the date of your death or the cause of your death?".to_string(),
            options: vec!["The date".to_string(), "The cause".to_string(), "Neither".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What's most important in a partner?".to_string(),
            options: vec!["Sense of humor".to_string(), "Ambition".to_string(), "Emotional intelligence".to_string(), "Shared interests".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather live 100 years in the past or 100 years in the future?".to_string(),
            options: vec!["100 years in the past".to_string(), "100 years in the future".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "How do you feel about long-distance friendships?".to_string(),
            options: vec!["They can thrive".to_string(), "They're hard but worth it".to_string(), "They usually fade".to_string()],
            min_affinity: 5,
            language: "en".to_string(),
            translatable: true,
        },

        // ========== TIER 3: min_affinity = 8 (Personal & philosophical) ==========
        Question {
            id: Uuid::new_v4(),
            text: "What's your biggest fear?".to_string(),
            options: vec!["Being alone".to_string(), "Failure".to_string(), "Losing loved ones".to_string(), "The unknown".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Do you think true selflessness exists?".to_string(),
            options: vec!["Yes".to_string(), "No, there's always a motive".to_string(), "It's complicated".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather have everyone forget who you are or forget everyone you know?".to_string(),
            options: vec!["Everyone forgets me".to_string(), "I forget everyone".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What do you think happens after we die?".to_string(),
            options: vec!["Nothing".to_string(), "Reincarnation".to_string(), "Afterlife".to_string(), "Something we can't comprehend".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Is it better to have loved and lost, or never to have loved at all?".to_string(),
            options: vec!["Loved and lost".to_string(), "Never loved at all".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What would you sacrifice for success?".to_string(),
            options: vec!["Time with family".to_string(), "Personal hobbies".to_string(), "Nothing, balance is key".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather be the smartest person in the room or the most likable?".to_string(),
            options: vec!["Smartest".to_string(), "Most likable".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "If you could change one thing about yourself, what area would it be?".to_string(),
            options: vec!["Appearance".to_string(), "Personality".to_string(), "Intelligence".to_string(), "Nothing".to_string()],
            min_affinity: 8,
            language: "en".to_string(),
            translatable: true,
        },

        // ========== TIER 4: min_affinity = 12 (Intimate / trust-based) ==========
        Question {
            id: Uuid::new_v4(),
            text: "What's a deal-breaker in a close relationship for you?".to_string(),
            options: vec!["Dishonesty".to_string(), "Lack of effort".to_string(), "Disrespect".to_string(), "Jealousy".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Do you think vulnerability is a strength or a weakness?".to_string(),
            options: vec!["Strength".to_string(), "Weakness".to_string(), "Depends on context".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What's the most important lesson life has taught you?".to_string(),
            options: vec!["Nothing is permanent".to_string(), "Be true to yourself".to_string(), "People matter most".to_string(), "Hard work always pays off".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you forgive someone who deeply betrayed you?".to_string(),
            options: vec!["Yes, always".to_string(), "Maybe, depends".to_string(), "No, never".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What keeps you up at night?".to_string(),
            options: vec!["Future worries".to_string(), "Past regrets".to_string(), "Excitement for tomorrow".to_string(), "Nothing, I sleep great".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "How do you express love or care?".to_string(),
            options: vec!["Words of affirmation".to_string(), "Quality time".to_string(), "Acts of service".to_string(), "Physical affection".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Would you rather be deeply understood by one person or generally liked by everyone?".to_string(),
            options: vec!["Deeply understood by one".to_string(), "Liked by everyone".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "If you could know one absolute truth about the universe, what topic would it be about?".to_string(),
            options: vec!["Life after death".to_string(), "Origin of consciousness".to_string(), "Whether we're alone in the universe".to_string(), "The meaning of it all".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "What do you think is the hardest part of being human?".to_string(),
            options: vec!["Dealing with loss".to_string(), "Finding purpose".to_string(), "Connecting with others".to_string(), "Accepting imperfection".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
        Question {
            id: Uuid::new_v4(),
            text: "Is it possible to love someone and still let them go?".to_string(),
            options: vec!["Yes, love means freedom".to_string(), "No, real love holds on".to_string(), "It depends on the situation".to_string()],
            min_affinity: 12,
            language: "en".to_string(),
            translatable: true,
        },
    ]
}
